
char DEFAULT_STX[] = ""
  "\n" "displayname: c"
  "\n" "extensions: .*\\.cpp$"
  "\n" "            .*\\.hpp$"
  "\n" "            .*\\.c$"
  "\n" "            .*\\.h$"
  "\n" "comment|no_sep: //.*$"
  "\n" "keyword: (restrict|switch|if|while|for|break|continue|return|else|try|catch|else|struct|union|class|typedef|static|enum|case|asm|default|delete|do|explicit|export|extern|inline|namespace|new|public|private|protected|sizeof|template|this|typedef|typeid|typename|using|virtual|friend|goto)"
  "\n" "type: (auto|bool|char|const|double|float|inline|int|mutable|register|short|unsigned|volatile|void|int8_t|int16_t|int32_t|int64_t|uint8_t|uint16_t|uint32_t|uint64_t|size_t|ssize_t|time_t)"
  "\n" "comment|no_sep: /\\*.*\\*/"
  "\n" "comment|no_sep: /\\*.*"
  "\n" "                 .*\\*/"
  "\n" "pragma: \\s*#(include|pragma|define|undef) .*$"
  "\n" "predefined: (NULL|stdout|stderr)"
  "\n" "pragma: \\s*#(ifdef|ifndef|if) .*$"
  "\n" "pragma: \\s*#(endif)"
  "\n" "string|no_sep: \"([^\\\\\\\"]|\\\\.)*\""
  "\n" "string|no_sep: '([^\\\\\\\']|\\\\.)'"
  "\n" "number: [+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)[fl]?"
  "\n"
  "\n" "split:"
  "\n"
  "\n" "displayname: md"
  "\n" "extensions: .*\\.md"
  "\n" "            .*\\.markdown"
  "\n" "pragma|no_sep: ```[^ ]*"
  "\n" "pragma|no_sep: #.*$"
  "\n" "number: \\*\\*[^(\\*\\*)]\\*\\*"
  "\n" "number: \\*[^\\*]\\*"
  "\n" "keyword: -\\s+"
;

